### ISSUE TITLE
INFOGRAFIA ANTONIA MARTINEZ SANDOVAL

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/actividad-1-infografia-2003lulu#2]
[Infografía_ ANTONIA MARTINEZ SANDOVAL_compressed.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-2003lulu/files/12581098/Infografia_.ANTONIA.MARTINEZ.SANDOVAL_compressed.pdf)

**Comment by 27Fer12** [comment]
partes de la infografía:
coherencia:4
organizacion:4
diseño:4
creatividad:3
calificación:19/20
Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
